### ISSUE TITLE
New line in Scancode output

### ISSUE THREAD

**Issue by fossygirl** [clearlydefined/crawler#280]
@pombredanne Take a look at the harvested data on line 1068 for https://clearlydefined.io/definitions/sourcearchive/mavencentral/net.razorvine/pyrolite/4.9

We are getting a new line in the declared_license which means we're calling this NOASSERTION erroneously.

@dabutvin

**Comment by dabutvin** [comment]
see `"declared_license":` in the snippet below

```
"packages": [
{
  "type": "maven",
  "namespace": "net.razorvine",
  "name": "pyrolite",
  "version": "4.9",
  "qualifiers": null,
  "subpath": null,
  "primary_language": "Java",
  "description": "pyrolite\nThis library allows your Java program to interface very easily with the Python world. It uses the Pyro protocol to call methods on remote objects. (See https://github.com/irmen/Pyro4). To that end, it also contains and uses a feature complete pickle protocol implementation -read and write- to exchange data with Pyro/Python.\n\nPyrolite only implements part of the client side Pyro library, hence its name 'lite'...  But because Pyrolite has no dependencies, it is a much lighter way to use Pyro from Java/.NET than a solution with jython+pyro or IronPython+Pyro would provide. So if you don't need Pyro's full feature set, and don't require your Java/.NET code to host Pyro objects itself, Pyrolite may be a good choice to connect java or .NET and python.",
  "release_date": null,
  "parties": [
    {
      "type": "person",
      "role": "developper",
      "name": "Irmen de Jong",
      "email": "irmen@razorvine.net",
      "url": "https://github.com/irmen"
    }
  ],
  "keywords": [],
  "homepage_url": "https://github.com/irmen/Pyrolite",
  "download_url": null,
  "size": null,
  "sha1": null,
  "md5": null,
  "sha256": null,
  "sha512": null,
  "bug_tracking_url": "https://github.com/irmen/Pyrolite/issues",
  "code_view_url": "https://github.com/irmen/Pyrolite",
  "vcs_url": "git+https://github.com/irmen/Pyrolite.git",
  "copyright": null,
  "license_expression": "mit AND unknown",
  "declared_license": "MIT License\nhttps://raw.githubusercontent.com/irmen/Pyrolite/master/LICENSE",
  "notice_text": null,
  "manifest_path": null,
```

**Comment by pombredanne** [comment]
Let me check this

**Comment by jeffmcaffer** [comment]
interestingly the `license_expression` is `mit AND unknown`

Aside, should we be looking at `unknown` as equivalent to NOASSERTION? 

Also, is `declared_license` an expression?

**Comment by pombredanne** [comment]
@fossygirl this is the data from http://central.maven.org/maven2/net/razorvine/pyrolite/4.9/pyrolite-4.9.pom which is in a Maven POM a list of <licenses> and each <license> item can have a name, url and comment.

In the current version 3.0.2, multiple values are joined with a new line which is not great as it does not preserve the original structure of the data (which could be a JSON string, array or object or combos of these). 

There is on-going work to improve this in ScanCode with https://github.com/nexB/scancode-toolkit/issues/1403 and in particular Maven and npm have been completed.

In this case ScanCode now returns this much better data now:
```
.....
          "license_expression": "mit",
          "declared_license": [
            {
              "name": "MIT License",
              "url": "https://raw.githubusercontent.com/irmen/Pyrolite/master/LICENSE",
              "comments": null,
              "distribution": null
            }
          ],
....
``` 


@jeffmcaffer you wrote

> Aside, should we be looking at unknown as equivalent to NOASSERTION?

yes this is the essence of a detection that is not conclusive. But this does not have an SPDX id so I would assume you treat this as such?

Otherwise, there are few other license keys that would be in this area such as  `unknown-license-reference` `free-unknown` and `other-copyleft` or `other-permissive`

> Also, is `declared_license` an expression?

In most cases, no. `declared_license` is the  data as declared in a package manifest, while `license_expression` the result of detecting the licenses in that `declared_license` data.   The  `declared_license` structure is not specified as this is representing whatever was in the original license declaration of a package manifest. 
So in the Maven case it will be a list of objects. In the case of npm it can be either a list of strings (some of which should be expressions) or a list of objects, or an object. In the case Rubygems, this is a list of strings, etc.

`license_expression`  is the field that you want to get a normalized expression from.

**Comment by jeffmcaffer** [comment]
Thanks for the detail @pombredanne

**Comment by nellshamrell** [comment]
Closing this due to the age of the issue, but please feel free to re-open if you are still seeing issues around this.
