### ISSUE TITLE
messages older than 7 days are expiring

### ISSUE THREAD

**Issue by dabutvin** [clearlydefined/crawler#293]
This is causing some unexpected behavior in the system. 

The old maximum for az storage queuing is 7 days, but recently you can set the maximum to -1 to get infinite ttl on queue messages.

I tried setting to -1 and this is not working with the current sdk.
We should take a look at https://github.com/Azure/azure-sdk-for-js/tree/master/sdk/storage/storage-queue to see if it will support increasing the ttl beyond 7 days

**Comment by jeffmcaffer** [comment]
double sigh. that we have messages in the queue for more than 7 days sucks. What problems is this causing (other than the messages not getting processed)? I'm almost ok with them getting dropped. This is a point in time problem and we should just throttle the queuing to avoid the issue. It is better practice anyway.

That is to say, rather than heroic measures to address the problem, perhaps just stop causing the problem?

**Comment by dabutvin** [comment]
> What problems is this causing

We are getting a lot of 'message does not exist' exceptions in the crawlers. I believe this is from trying to delete the messages when we are done, but they are already gone

It's a side affect of having filled up a foreground and a background queue.
The high-pri queue is about 1.25 days behind
The low pri queue is up to 7 days behind and the top messages are actively expiring.

**Comment by dabutvin** [comment]
I think it would be worth it to see if this new sdk can successfully set -1 as the ttl to set it to infinite.

If that does not work, we should work around the problem, but if it does work - probably worth swapping out sdks.

**Comment by geneh** [comment]
We're not worried about 7 day old messages anymore.
