### ISSUE TITLE
Add crawler support for Debian package & source

### ISSUE THREAD

**Issue by geneh** [clearlydefined/crawler#321]
The new coordinates should be as follows.
**Package** `cd:/deb/debian/-/<name>/<version>` where the version is `<version>_<architecture>`, for example all, 1.1.0_amd64, 1.1.0_i386, 1.1.0_armel etc.
**Source** `cd:/debsrc/debian/-/<name>/<version>`.

Debian also has a concept of an area, for example main and contrib, but it probably shouldn't be a part of the coordinates in package and source cases.

In the future, the coordinates for Ubuntu would be `cd:/deb/ubuntu/...` and `cd:/debsrc/ubuntu...` (not part of this feature work).

#### High level algorithm:
- If a package or a source version is not provided, retrieve it from https://sources.debian.org/api/src/NAME/latest, for example https://sources.debian.org/api/src/amoeba/latest. More details: https://sources.debian.org/doc/api/
- Download, unzip and store locally package-file.map file from http://ftp.debian.org/debian/indices/package-file.map.bz2. The file should be cached, for example by using an ETag and keeping the most recent Etag in memory. The file may be parsed by https://github.com/clearlydefined/dpkg-parser or a similar solution.
- In order to find the location of the package and the source:
**Package**: look for entries with Architecture, Binary and Binary-Version. For example, for the following package:
```
Path: ./pool/main/2/2048-qt/2048-qt_0.1.6-2_arm64.deb
Source: 2048-qt
Source-Version: 0.1.6-2
Architecture: arm64
Binary: 2048-qt
Binary-Version: 0.1.6-2
```
the binary can be fetched from http://ftp.debian.org/debian/pool/main/2/2048-qt/2048-qt_0.1.6-2_arm64.deb:
```
curl -L http://ftp.debian.org/debian/pool/main/2/2048-qt/2048-qt_0.1.6-2_arm64.deb | tar zx
ls -l
total 4272
-rw-r--r--  1 gene  staff     1172 Apr  9 10:51 control.tar.xz
-rw-r--r--  1 gene  staff  1390812 Apr  9 10:51 data.tar.xz
-rw-r--r--  1 gene  staff        4 Apr  9 10:51 debian-binary
```
The binaries will be inside data.tar.xz which should be extracted: `tar -xf data.tar.xz`.
**Source**: look for entries without Architecture or Binary. For example, for the following source:
```
Path: ./pool/main/2/2048-qt/2048-qt_0.1.6-1.debian.tar.xz
Source: 2048-qt
Source-Version: 0.1.6-1

Path: ./pool/main/2/2048-qt/2048-qt_0.1.6-1.dsc
Source: 2048-qt
Source-Version: 0.1.6-1

Path: ./pool/main/2/2048-qt/2048-qt_0.1.6.orig.tar.gz
Source: 2048-qt
Source-Version: 0.1.6-1
```
the path would contain ".orig." and the rest of the paths with the same Source and Source-Version would be the patches, except for the .dsc file which can be ignored for now.
The patches have to be applied as following:
```
curl -L http://ftp.debian.org/debian/pool/main/2/2048-qt/2048-qt_0.1.6.orig.tar.gz | tar zx
curl -L http://ftp.debian.org/debian/pool/main/2/2048-qt/2048-qt_0.1.6-1.debian.tar.xz | tar zx

ls -l
drwxr-xr-x  14 gene  staff        448 Sep 18  2015 2048-Qt-0.1.6 <-- source
drwxr-xr-x  14 gene  staff        448 Nov 26  2015 debian <-- patch

cd ./2048-Qt-0.1.6 

cat ../debian/patches/series 
FixDesktop.diff
FixPathBinary.diff

patch -p01 -i ../debian/patches/FixDesktop.diff
patch -p01 -i ../debian/patches/FixPathBinary.diff
```
- Run all the tools like scancode etc.

**Comment by geneh** [comment]
package, src, and patches info should be captured via APIs, for example:
https://sources.debian.org/api/info/package/amoeba/1.1-30/

https://sources.debian.org/api/src/amoeba/1.1-30/
https://sources.debian.org/patches/api/amoeba/1.1-30/ - note that the patches are already listed in the right order.

**Comment by fossygirl** [comment]
We will maintain the architecture for the package because otherwise there could be ambiguity in licensing and we'll do so in the namespace.

**Comment by storrisi** [comment]
@fossygirl @geneh just a few questions:

- we have some behaviors on the website that allows a user to drop a URL on the components list to get a specific package, by parsing the URL into a path string. Since a Debian source package URL doesn't contain a specific architecture (for example https://sources.debian.org/src/async-http-client/2.6.0-1/ ), how should we define what kind of architecture we need? Perhaps we can introduce a "*" namespace identifier? 

- In the Debian specific case, we could easily have the same curation changes on different namespaces (i guess). So probably, we should consider improving the suggestion workflow including also suggestions for different namespaces of the same component?

**Comment by geneh** [comment]
@storrisi @pombredanne @ignacionr 
I see now where the concern is. Regarding Debian packages, would it make sense to support dropping URLs such as http://ftp.debian.org/debian/pool/main/2/2048-qt/2048-qt_0.1.6-1+b1_i386.deb?
Does the following make more sense as some of you have suggested (architecture appended to version instead of the namespace)? `cd:/deb/debian/-/<name>/<version>_<architecture>`, for example `cd:/deb/debian/-/2048-qt/0.1.6-1+b1_i386.`

Note to self: need to check how versions with special characters, e.g. +, are going to work, especially with blob storage etc.

**Comment by storrisi** [comment]
> would it make sense to support dropping URLs such as http://ftp.debian.org/debian/pool/main/2/2048-qt/2048-qt_0.1.6-1+b1_i386.deb?

It does for me. If we agree, I can easily implement a method to parse it, but the curators should know that they can drop this kind of URLs.

>Does the following make more sense as some of you have suggested (architecture appended to version instead of the namespace)? cd:/deb/debian/-/<name>/<version>_<architecture>, for example cd:/deb/debian/-/2048-qt/0.1.6-1+b1_i386.

Looks better, with this structure we can think to the architecture as an extension of the version, this would make sense also for suggestions during curations.

**Comment by geneh** [comment]
Great, Ive updated the description: 
**Package** `cd:/deb/debian/-/<name>/<version>` where the version is `<version>_<architecture>`, for example all, 1.1.0_amd64, 1.1.0_i386, 1.1.0_armel etc.

**Comment by pombredanne** [comment]
@geneh I thought I posted a comment there... but I had not. Sorry for that!
My opinion is that architecture is a least significant data point in the naming of Debian packages and but this is also the case for RPMs... think NEVRA for RPMs that lists data items in order from most to least significant: Name, Epoch, Version, Release, Architecture where arch comes last. That's also how it has been treated in [Package URLs.](https://github.com/package-url). And most and foremost this is how this shows up in a built package archive filename: it comes last after an extension such as `zlib1g-dbg_1.2.11.dfsg-1_s390x.deb` for a System 390 ;) 

Something like the `Distribution` (e.g. stable/testing in Debian or disco/bionic/..in Ubuntu) could be something that could be used as the namespace, though in Debian the pool of packages is not specific to any distro.

The key thing is that that there are  several essential related files for any given debian package:

1. one or more binary/built package (some of which may be architecture-specific)
2. one original source archive: the source code
3. one debian tarball with the control, copyright and possible patch files:  the metadata and part of the source code.
4. one dsc file that is the "index" linking the 1, 2 and 3 together

You cannot deal with 1. binaries correctly without scanning also 2. and 3.
Where will you store 3. and 4.? 
And will you also consider 2. as a package (that is curated and scanned)?

From a scanning and curation POV, it does not make sense to look at one in the abstract of the other IMHO.

Also note that a better URL is http://deb.debian.org/debian/pool/main/2/2048-qt/2048-qt_0.1.6-1+b1_i386.deb rather than http://ftp.debian.org/debian/pool/main/2/2048-qt/2048-qt_0.1.6-1+b1_i386.deb because it goes to a CDN but IMHO both should be accepted as URL that can entered 


Finally you could very much rsync it all to stay polite rather than fetching things through JSON from `sources` which is much a second-level data source anyway.

**Comment by geneh** [comment]
@pombredanne Regarding fetching things through JSON from sources, that should be very rare. The only case would be when the version isn't provided, which would ideally never happen.

Regarding separation of binary and source code, I think we agree that packages source code along with their patches should be scanned. 
Do you think scancode won't be able to detect licensing data etc. without scanning the sources too? Do you suggest scanning binaries along with their sources each time or do you mean the website and the service will have to be updated to link the detected data from both binaries and their sources?
