### ISSUE TITLE
Packages in Preview not being queued for harvesting

### ISSUE THREAD

**Issue by ariel11** [clearlydefined/crawler#325]
These two packages are not being queued for harvesting.  @geneh identified the issue as "As for the packages below, these are preview versions, so these versions are not displayed in https://clearlydefined.io/harvest page when trying to pick a version."

https://www.nuget.org/packages/Microsoft.NETCore.Platforms

https://clearlydefined.io/definitions/nuget/nuget/-/microsoft.powershell.native/7.0.0-preview.1

**Comment by geneh** [comment]
It only happens to some NuGet pre-released versions. The versions are not listed, so the components cannot be harvested:
https://api.nuget.org/v3/registration3/microsoft.netcore.platforms/index.json
https://api.nuget.org/v3/registration3/microsoft.powershell.native/index.json
Trying to figure out if there is a workaround...

**Comment by geneh** [comment]
https://api.nuget.org/v3/index.json
The following API should be used instead:
```
    {
      "@id": "https://api.nuget.org/v3/registration3-gz-semver2/",
      "@type": "RegistrationsBaseUrl/Versioned",
      "clientVersion": "4.3.0-alpha",
      "comment": "Base URL of Azure storage where NuGet package registration info is stored in GZIP format. This base URL includes SemVer 2.0.0 packages."
    },
```

**Comment by geneh** [comment]
These packages are now getting harvested.
Dev env:
https://dev.clearlydefined.io/definitions/nuget/nuget/-/microsoft.netcore.platforms/3.0.0-preview5.19224.8
https://dev.clearlydefined.io/definitions/nuget/nuget/-/microsoft.powershell.native/7.0.0-preview.1
They have been queued in production but it may take a while since there are many messages in the queue right now.
