### ISSUE TITLE
Update licensee scan tool

### ISSUE THREAD

**Issue by qtomlinson** [clearlydefined/crawler#536]
[licensee](https://github.com/licensee/licensee) is used in the crawler as one of the scanning tools.

The current version of licensee used in production crawler is 9.12, and the latest released is v9.16.1. As part of the [update crawler dependencies](https://github.com/clearlydefined/crawler/issues/528), upgrading helps with the following:
- Improved license detection.
- The latest release supports Ruby 3.22 (see https://github.com/licensee/licensee/releases/tag/v9.16.1). Upgrading will likely enable the building of a Docker image based on node:18 (instead of node:18-bullseye).

**Comment by yashkohli88** [comment]
Following steps have been completed as a part of licensee upgrade activity - 

- [x] No changes in Input or Output format from 9.12.0 to 9.16.1. Verified using change log. 
- [x] Ruby is upgraded to 3.2.2 and bundler to 2.5.4. All other dependency of licensee also updated to their latest version 
- [x] The updates were limited to Dockerfile and DevDockerfile, no code changes were needed. 
- [x] Tested around 200 test cases for Licensee in crawler including all types of repos More than 95% of the test cases yielded same output as previous version Few cases reported better license detection with exact matches compared to previous version and few reported with lesser confidence for some files. 
- [x] No significant change in memory footprint ranging from 97 to 116% when compared to the previous version. 
- [x] Ran sanity test with full harvest for few of the test cases and compared the definition API response for differences. All of the test cases were found to be same as the previous version. The test cases with difference in Licensee tool also had the same response in definition API. 
- [x] This upgrade enable us to use standard Node 18 image, testing for Licensee with standard Node 18 image is also completed but could not be updated due to some compatibility issue of Scancode.

Pull request for this issue has been created and submitted. [#549 ](https://github.com/clearlydefined/crawler/pull/549)

**Comment by yashkohli88** [comment]
Attaching Detailed testing documentation along with the list of coordinates used for testing.

[Licensee Testing Documentation.docx](https://github.com/clearlydefined/crawler/files/14349228/Licensee.Testing.Documentation.docx)
- Unit Testing and comparison of Licensee
- Significant Results and conclusion from Testing
- Steps to get peak memory footprint
- Integration Testing using definitions API

Coordinates used for performing the above testing -
[test-cooridnates.csv](https://github.com/clearlydefined/crawler/files/14349282/test-cooridnates.csv)
